jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Login to Hugging Face
        run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

      - name: Push to Hugging Face
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git remote add hf https://huggingface.co/spaces/your-username/your-app-name
          git push hf main
