name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Launch App
        env:
          HF_TOKEN: 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
        run: |
          pip install huggingface_hub
          huggingface-cli login --token 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
          huggingface-cli repo create mini-gpt-lab --type=space --sdk=streamlit --private
          huggingface-cli upload mini-gpt-lab . --repo-type=space --commit-message "Initial Deploy"
